<template>
  <div class="min-h-[calc(100vh-60px)] bg-slate-50 px-4 py-5 sm:px-6">
    <div class="mx-auto">
      <!-- Header -->
      <div class="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between">
        <div class="min-w-0">
          <div class="flex items-center gap-2">
            <span class="material-icons text-slate-700">edit_note</span>
            <h1 class="truncate text-lg font-extrabold text-slate-900 sm:text-xl">
              {{ isEdit ? "Edit Payment" : "Create Payment" }}
            </h1>
          </div>
          <p class="mt-1 text-sm text-slate-500">
            Fields follow the payments table: invoice_id, amount, method, currency, status, references…
          </p>
        </div>

        <div class="flex items-center gap-2">
          <button
            class="rounded-full bg-white/70 px-4 py-2 text-sm font-bold text-slate-700 hover:bg-white"
            type="button"
            @click="goBack"
          >
            Back
          </button>

          <button
            class="rounded-full bg-slate-900 px-4 py-2 text-sm font-bold text-white hover:bg-slate-800"
            type="button"
            @click="save"
          >
            {{ isEdit ? "Update" : "Save" }}
          </button>
        </div>
      </div>

      <!-- Form -->
      <div class="mt-4 grid gap-3">
        <!-- Top (no border/shadow) -->
        <div class="rounded-2xl bg-white/70 p-4">
          <div class="grid gap-3 sm:grid-cols-12">
            <div class="sm:col-span-6">
              <label class="text-xs font-bold text-slate-600">Payment Number</label>
              <input v-model="form.payment_number" class="field" placeholder="PAYYYYYMMDD-..." />
              <p class="hint">Unique identifier. In real API it is generated by server/trigger.</p>
            </div>

            <div class="sm:col-span-3">
              <label class="text-xs font-bold text-slate-600">Property ID</label>
              <input v-model.number="form.property_id" type="number" class="field" placeholder="1" />
            </div>

            <div class="sm:col-span-3">
              <label class="text-xs font-bold text-slate-600">Invoice ID</label>
              <input v-model.number="form.invoice_id" type="number" class="field" placeholder="1" />
            </div>
          </div>
        </div>

        <div class="rounded-2xl bg-white/70 p-4">
          <div class="grid gap-3 sm:grid-cols-12">
            <div class="sm:col-span-4">
              <label class="text-xs font-bold text-slate-600">Amount</label>
              <input v-model.number="form.amount" type="number" step="0.01" class="field" placeholder="0.00" />
            </div>

            <div class="sm:col-span-4">
              <label class="text-xs font-bold text-slate-600">Method</label>
              <select v-model="form.payment_method" class="field">
                <option v-for="m in METHODS" :key="m" :value="m">{{ m }}</option>
              </select>
            </div>

            <div class="sm:col-span-4">
              <label class="text-xs font-bold text-slate-600">Status</label>
              <select v-model="form.status" class="field">
                <option v-for="s in STATUSES" :key="s" :value="s">{{ s }}</option>
              </select>
            </div>
          </div>

          <div class="mt-3 grid gap-3 sm:grid-cols-12">
            <div class="sm:col-span-3">
              <label class="text-xs font-bold text-slate-600">Currency</label>
              <select v-model="form.payment_currency" class="field">
                <option value="USD">USD</option>
                <option value="KHR">KHR</option>
              </select>
            </div>

            <div class="sm:col-span-3">
              <label class="text-xs font-bold text-slate-600">Exchange Rate</label>
              <input v-model.number="form.exchange_rate" type="number" step="0.0001" class="field" />
            </div>

            <div class="sm:col-span-6">
              <label class="text-xs font-bold text-slate-600">Amount in Base Currency</label>
              <input v-model.number="form.amount_in_base_currency" type="number" step="0.01" class="field" />
              <p class="hint">Optional: store converted value for reporting.</p>
            </div>
          </div>
        </div>

        <div class="rounded-2xl bg-white/70 p-4">
          <div class="grid gap-3 sm:grid-cols-12">
            <div class="sm:col-span-6">
              <label class="text-xs font-bold text-slate-600">Reference Number</label>
              <input v-model="form.reference_number" class="field" placeholder="ABA-TRX-..." />
            </div>

            <div class="sm:col-span-6">
              <label class="text-xs font-bold text-slate-600">Card Type (if card)</label>
              <input v-model="form.card_type" class="field" placeholder="VISA / MasterCard..." />
            </div>

            <div class="sm:col-span-6">
              <label class="text-xs font-bold text-slate-600">Payment Date</label>
              <input v-model="form.payment_date" class="field" placeholder="YYYY-MM-DD HH:mm:ss" />
            </div>

            <div class="sm:col-span-6">
              <label class="text-xs font-bold text-slate-600">Processed By (user_id)</label>
              <input v-model.number="form.processed_by" type="number" class="field" placeholder="1" />
            </div>

            <div class="sm:col-span-12">
              <label class="text-xs font-bold text-slate-600">Notes</label>
              <textarea v-model="form.notes" rows="3" class="field" placeholder="Optional notes…"></textarea>
            </div>
          </div>
        </div>

        <div class="rounded-2xl bg-white/70 p-4">
          <div class="text-xs font-bold text-slate-600">System fields</div>
          <div class="mt-2 grid gap-3 sm:grid-cols-12">
            <div class="sm:col-span-4">
              <label class="text-xs font-bold text-slate-600">created_at</label>
              <input v-model="form.created_at" class="field" placeholder="YYYY-MM-DD HH:mm:ss" />
            </div>
            <div class="sm:col-span-4">
              <label class="text-xs font-bold text-slate-600">updated_at</label>
              <input v-model="form.updated_at" class="field" placeholder="YYYY-MM-DD HH:mm:ss" />
            </div>
            <div class="sm:col-span-4">
              <label class="text-xs font-bold text-slate-600">payment_id</label>
              <input :value="form.payment_id ?? 'Auto'" class="field" disabled />
            </div>
          </div>
        </div>

        <!-- Local demo notice -->
        <div class="rounded-2xl bg-white/70 p-4 text-sm text-slate-600">
          <b>Note:</b> This is a UI demo using static data. The “Save/Update” button currently just logs data.
          When you connect API, you will POST/PUT to backend and then refresh list.
        </div>
      </div>

    </div>
  </div>
</template>

<script setup>
import { computed, onMounted, reactive } from "vue"
import { useRoute, useRouter } from "vue-router"
import { payments as staticPayments } from "@/data/billding/payments"

const route = useRoute()
const router = useRouter()

const METHODS = ["cash", "credit_card", "debit_card", "bank_transfer", "aba", "wing", "true_money", "pi_pay", "other"]
const STATUSES = ["pending", "completed", "failed", "refunded", "cancelled"]

const isEdit = computed(() => !!route.params.paymentId)

const form = reactive({
  payment_id: null,
  property_id: 1,
  invoice_id: 1,
  payment_number: "",
  amount: 0,
  payment_method: "cash",
  payment_currency: "USD",
  exchange_rate: 1,
  amount_in_base_currency: 0,
  reference_number: "",
  card_type: "",
  payment_date: "",
  status: "completed",
  notes: "",
  processed_by: 1,
  created_at: "",
  updated_at: ""
})

onMounted(() => {
  if (!isEdit.value) {
    // create default demo values
    const now = new Date()
    const dt = toSql(now)
    form.payment_date = dt
    form.created_at = dt
    form.updated_at = dt
    form.payment_number = genPaymentNo(now)
    form.amount_in_base_currency = form.amount
    return
  }

  const id = Number(route.params.paymentId)
  const found = staticPayments.find(p => Number(p.payment_id) === id)
  if (!found) {
    router.replace({ name: "billing-payments" })
    return
  }

  Object.assign(form, JSON.parse(JSON.stringify(found)))
})

function toSql(d) {
  const pad = (n) => String(n).padStart(2, "0")
  return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())} ${pad(d.getHours())}:${pad(d.getMinutes())}:${pad(d.getSeconds())}`
}

function genPaymentNo(d) {
  const pad = (n) => String(n).padStart(2, "0")
  const y = d.getFullYear()
  const m = pad(d.getMonth() + 1)
  const day = pad(d.getDate())
  return `PAY${y}${m}${day}-001-000999`
}

function goBack() {
  router.push({ name: "billing-payments" })
}

function save() {
  // demo only
  // when API exists:
  // - create: POST /payments
  // - edit: PUT /payments/:id
  // then navigate back + refresh list
  console.log("SAVE PAYMENT:", { ...form })
  goBack()
}
</script>

<style scoped>
.field {
  width: 100%;
  margin-top: 6px;
  border: 0;
  outline: none;
  background: rgba(255, 255, 255, 0.6);
  border-radius: 9999px;
  padding: 10px 14px;
  font-size: 14px;
  color: #0f172a;
}
.field:focus {
  background: rgba(255, 255, 255, 0.95);
}
textarea.field {
  border-radius: 18px;
}
.hint {
  margin-top: 6px;
  font-size: 12px;
  color: #64748b;
}
</style>
